sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jhashailesh3108/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true jhashailesh3108/docker-react npm run test
